# Generated by Django 4.0.4 on 2022-05-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_name', models.CharField(max_length=100, verbose_name='Континент')),
                ('slug_name', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Текст статьи')),
            ],
            options={
                'verbose_name': 'Континенты',
                'verbose_name_plural': 'Континенты',
                'ordering': ('cont_name',),
            },
        ),
        migrations.CreateModel(
            name='Cityinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('population', models.IntegerField(verbose_name='Численность населения')),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.continents', verbose_name='id континента')),
            ],
            options={
                'verbose_name': 'Города',
                'verbose_name_plural': 'Города',
                'ordering': ('city',),
            },
        ),
    ]
